#ifndef __1290_CONVERT_BINARY_NUMBER_IN_A_LINKED_LIST_TO_INTEGER_H__
#define __1290_CONVERT_BINARY_NUMBER_IN_A_LINKED_LIST_TO_INTEGER_H__

int getDecimalValue (struct ListNode * head);

#endif /* __1290_CONVERT_BINARY_NUMBER_IN_A_LINKED_LIST_TO_INTEGER_H__ */
