#ifndef INCLUDED_2147_NUMBER_OF_WAYS_TO_DIVIDE_A_LONG_CORRIDOR_H_
#define INCLUDED_2147_NUMBER_OF_WAYS_TO_DIVIDE_A_LONG_CORRIDOR_H_

int numberOfWays (char * corridor);

#endif  /* INCLUDED_2147_NUMBER_OF_WAYS_TO_DIVIDE_A_LONG_CORRIDOR_H_ */
