#ifndef INCLUDED_1637_WIDEST_VERTICAL_AREA_BETWEEN_TWO_POINTS_CONTAINING_NO_POINTS_H_
#define INCLUDED_1637_WIDEST_VERTICAL_AREA_BETWEEN_TWO_POINTS_CONTAINING_NO_POINTS_H_

int maxWidthOfVerticalArea (int ** points, int pointsSize, int * pointsColSize);

#endif  /* INCLUDED_1637_WIDEST_VERTICAL_AREA_BETWEEN_TWO_POINTS_CONTAINING_NO_POINTS_H_ */
