#ifndef INCLUDED_1759_COUNT_NUMBER_OF_HOMOGENOUS_SUBSTRINGS_H_
#define INCLUDED_1759_COUNT_NUMBER_OF_HOMOGENOUS_SUBSTRINGS_H_

int countHomogenous (char * s);

#endif  /* INCLUDED_1759_COUNT_NUMBER_OF_HOMOGENOUS_SUBSTRINGS_H_ */
