#ifndef INCLUDED_2091_REMOVING_MINIMUM_AND_MAXIMUM_FROM_ARRAY_H_
#define INCLUDED_2091_REMOVING_MINIMUM_AND_MAXIMUM_FROM_ARRAY_H_

int minimumDeletions (int * nums, int numsSize);

#endif  /* INCLUDED_2091_REMOVING_MINIMUM_AND_MAXIMUM_FROM_ARRAY_H_ */
