#ifndef INCLUDED_028_FIND_THE_INDEX_OF_THE_FIRST_OCCURRENCE_IN_A_STRING_H_
#define INCLUDED_028_FIND_THE_INDEX_OF_THE_FIRST_OCCURRENCE_IN_A_STRING_H_

int strStr (char * haystack, char * needle);

#endif  /* INCLUDED_028_FIND_THE_INDEX_OF_THE_FIRST_OCCURRENCE_IN_A_STRING_H_ */
