#ifndef INCLUDED_083_REMOVE_DUPLICATES_FROM_SORTED_LIST_H_
#define INCLUDED_083_REMOVE_DUPLICATES_FROM_SORTED_LIST_H_

struct ListNode * deleteDuplicates (struct ListNode* head);

#endif /* __083_REMOVE_DUPLICATES_FROM_SORTED_LIST_H__ */
