#ifndef INCLUDED_1913_MAXIMUM_PRODUCT_DIFFERENCE_BETWEEN_TWO_PAIRS_H_
#define INCLUDED_1913_MAXIMUM_PRODUCT_DIFFERENCE_BETWEEN_TWO_PAIRS_H_

int maxProductDifference (int * nums, int numsSize);

#endif  /* INCLUDED_1913_MAXIMUM_PRODUCT_DIFFERENCE_BETWEEN_TWO_PAIRS_H_ */
