#ifndef INCLUDED_387_FIRST_UNIQUE_CHARACTER_IN_A_STRING_H_
#define INCLUDED_387_FIRST_UNIQUE_CHARACTER_IN_A_STRING_H_

int firstUniqChar(char * s);

#endif  /* INCLUDED_387_FIRST_UNIQUE_CHARACTER_IN_A_STRING_H_ */
